[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/post/*"
  to = "/.netlify/functions/redirect/:splat"
  status = 301
  force = true
